CREATE DATABASE LOCADORA

USE LOCADORA

CREATE TABLE CLIENTE(
	id INT PRIMARY KEY IDENTITY,
	nome VARCHAR(100),
	cpf VARCHAR(14),
	dataNascimento VARCHAR(100),
	endereco VARCHAR(100)
)

CREATE TABLE CATEGORIA(
	id INT PRIMARY KEY IDENTITY,
	descricao VARCHAR(30)
)

CREATE TABLE FILME(
	id INT PRIMARY KEY IDENTITY,
	categoriaId INT NOT NULL,
	descricao VARCHAR(50) NOT NULL,
	duracao TIME NOT NULL,
	valor DECIMAL(10,2) NOT NULL,
    FOREIGN KEY(categoriaId) REFERENCES CATEGORIA(ID)
)

CREATE TABLE FITA(
	id INT PRIMARY KEY IDENTITY,
	filmeId INT NOT NULL,
	descricao VARCHAR(20) NOT NULL,
	dataCompra DATE NOT NULL,
	FOREIGN KEY(filmeId) REFERENCES FILME(id)
)

CREATE TABLE LOCACAO(
	clienteId INT NOT NULL,
	fitaId INT NOT NULL,
	dataLocacao DATE NOT NULL,
	PRIMARY KEY(clienteId, fitaId),
	FOREIGN KEY(clienteId) REFERENCES CLIENTE(id),
	FOREIGN KEY(fitaId) REFERENCES FITA(id)
)